#!/usr/bin/env python3
"""Regenerates Sources/AmcuCore/ExtensionBundle.swift from extension/ and
Sources/AmcuCore/SafariExtensionBundle.swift from safari/extension/.

The browser extension ships inside the amcu binary so that `amcu browser
install` can always write the copy that matches the binary's protocol — a
single file to copy stays a single file to copy. Run this after editing
anything under extension/ or safari/extension/; the test suite checks they are
in sync. The Safari extension reuses the Chrome extension's content script and
icons (listed in SAFARI_SHARED) rather than carrying copies of them.
"""
import base64, hashlib, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'extension')
OUT = os.path.join(ROOT, 'Sources', 'AmcuCore', 'ExtensionBundle.swift')
SAFARI_SRC = os.path.join(ROOT, 'safari', 'extension')
SAFARI_OUT = os.path.join(ROOT, 'Sources', 'AmcuCore', 'SafariExtensionBundle.swift')
SAFARI_SHARED = ['content.js', 'icon16.png', 'icon48.png', 'icon128.png']

TEXT = {'.json', '.js', '.html', '.css', '.md'}

manifest = json.load(open(os.path.join(SRC, 'manifest.json')))
key_der = base64.b64decode(manifest['key'])
ext_id = ''.join(chr(ord('a') + int(c, 16)) for c in hashlib.sha256(key_der).hexdigest()[:32])

def collect(src):
    entries = []
    for name in sorted(os.listdir(src)):
        path = os.path.join(src, name)
        if not os.path.isfile(path) or name.startswith('.'):
            continue
        ext = os.path.splitext(name)[1]
        data = open(path, 'rb').read()
        if ext in TEXT:
            text = data.decode('utf-8')
            # Pick a raw-string delimiter the content cannot terminate.
            hashes = '#'
            while ('"""' + hashes) in text:
                hashes += '#'
            literal = f'{hashes}"""\n{text}\n"""{hashes}'
            entries.append((name, False, literal))
        else:
            literal = '"' + base64.b64encode(data).decode() + '"'
            entries.append((name, True, literal))
    return entries

entries = collect(SRC)

lines = []
lines.append('// GENERATED by Scripts/embed-extension.py from extension/ — do not edit by hand.')
lines.append('//')
lines.append('// The browser extension travels inside the binary so `amcu browser install`')
lines.append('// always writes the version that speaks this binary\'s protocol.')
lines.append('')
lines.append('import Foundation')
lines.append('')
lines.append('public enum ExtensionBundle {')
lines.append(f'    public static let version = "{manifest["version"]}"')
lines.append(f'    public static let id = "{ext_id}"')
lines.append(f'    public static let name = {json.dumps(manifest["name"])}')
lines.append('')
lines.append('    public struct File {')
lines.append('        public let name: String')
lines.append('        public let isBase64: Bool')
lines.append('        public let content: String')
lines.append('        public var data: Data {')
lines.append('            isBase64 ? (Data(base64Encoded: content) ?? Data()) : Data(content.utf8)')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    public static let files: [File] = [')
for name, is_b64, literal in entries:
    lines.append(f'        File(name: "{name}", isBase64: {"true" if is_b64 else "false"}, content: {literal}),')
lines.append('    ]')
lines.append('}')
open(OUT, 'w').write('\n'.join(lines) + '\n')
print(f'wrote {os.path.relpath(OUT, ROOT)}: {len(entries)} files, extension {manifest["version"]} id {ext_id}')

safari_manifest = json.load(open(os.path.join(SAFARI_SRC, 'manifest.json')))
if safari_manifest['version'] != manifest['version']:
    sys.exit(f"safari/extension/manifest.json is {safari_manifest['version']} but extension/manifest.json is {manifest['version']}")
for name in SAFARI_SHARED:
    if not os.path.isfile(os.path.join(SRC, name)):
        sys.exit(f'shared file extension/{name} is missing')
    if os.path.exists(os.path.join(SAFARI_SRC, name)):
        sys.exit(f'safari/extension/{name} shadows the shared extension/{name}; delete the copy')
safari_entries = collect(SAFARI_SRC)
lines = []
lines.append('// GENERATED by Scripts/embed-extension.py from safari/extension/ — do not edit by hand.')
lines.append('//')
lines.append('// The Safari extension\'s own files. The content script and icons are shared')
lines.append('// with the Chrome extension and come from ExtensionBundle (see sharedWithChrome).')
lines.append('')
lines.append('import Foundation')
lines.append('')
lines.append('public enum SafariExtensionBundle {')
lines.append(f'    public static let version = "{safari_manifest["version"]}"')
lines.append(f'    public static let sharedWithChrome = {json.dumps(SAFARI_SHARED)}')
lines.append('')
lines.append('    public static let files: [ExtensionBundle.File] = [')
for name, is_b64, literal in safari_entries:
    lines.append(f'        ExtensionBundle.File(name: "{name}", isBase64: {"true" if is_b64 else "false"}, content: {literal}),')
lines.append('    ]')
lines.append('}')
open(SAFARI_OUT, 'w').write('\n'.join(lines) + '\n')
print(f'wrote {os.path.relpath(SAFARI_OUT, ROOT)}: {len(safari_entries)} files + {len(SAFARI_SHARED)} shared, extension {safari_manifest["version"]}')
