#!/usr/bin/env python3
"""Regenerates Sources/AmcuCore/ExtensionBundle.swift from extension/.

The browser extension ships inside the amcu binary so that `amcu browser
install` can always write the copy that matches the binary's protocol — a
single file to copy stays a single file to copy. Run this after editing
anything under extension/; the test suite checks the two are in sync.
"""
import base64, hashlib, json, os, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'extension')
OUT = os.path.join(ROOT, 'Sources', 'AmcuCore', 'ExtensionBundle.swift')

TEXT = {'.json', '.js', '.html', '.css', '.md'}

manifest = json.load(open(os.path.join(SRC, 'manifest.json')))
key_der = base64.b64decode(manifest['key'])
ext_id = ''.join(chr(ord('a') + int(c, 16)) for c in hashlib.sha256(key_der).hexdigest()[:32])

entries = []
for name in sorted(os.listdir(SRC)):
    path = os.path.join(SRC, name)
    if not os.path.isfile(path) or name.startswith('.'):
        continue
    ext = os.path.splitext(name)[1]
    data = open(path, 'rb').read()
    if ext in TEXT:
        text = data.decode('utf-8')
        # Pick a raw-string delimiter the content cannot terminate.
        hashes = '#'
        while ('"""' + hashes) in text:
            hashes += '#'
        literal = f'{hashes}"""\n{text}\n"""{hashes}'
        entries.append((name, False, literal))
    else:
        literal = '"' + base64.b64encode(data).decode() + '"'
        entries.append((name, True, literal))

lines = []
lines.append('// GENERATED by Scripts/embed-extension.py from extension/ — do not edit by hand.')
lines.append('//')
lines.append('// The browser extension travels inside the binary so `amcu browser install`')
lines.append('// always writes the version that speaks this binary\'s protocol.')
lines.append('')
lines.append('import Foundation')
lines.append('')
lines.append('public enum ExtensionBundle {')
lines.append(f'    public static let version = "{manifest["version"]}"')
lines.append(f'    public static let id = "{ext_id}"')
lines.append(f'    public static let name = {json.dumps(manifest["name"])}')
lines.append('')
lines.append('    public struct File {')
lines.append('        public let name: String')
lines.append('        public let isBase64: Bool')
lines.append('        public let content: String')
lines.append('        public var data: Data {')
lines.append('            isBase64 ? (Data(base64Encoded: content) ?? Data()) : Data(content.utf8)')
lines.append('        }')
lines.append('    }')
lines.append('')
lines.append('    public static let files: [File] = [')
for name, is_b64, literal in entries:
    lines.append(f'        File(name: "{name}", isBase64: {"true" if is_b64 else "false"}, content: {literal}),')
lines.append('    ]')
lines.append('}')
open(OUT, 'w').write('\n'.join(lines) + '\n')
print(f'wrote {os.path.relpath(OUT, ROOT)}: {len(entries)} files, extension {manifest["version"]} id {ext_id}')
